### ISSUE TITLE
[FEAT] A 404 Page for the Website.

### ISSUE THREAD

**Issue by sukumar1210** [VRARMR-juet/VRARMR-juet.github.io#10]
**Is your feature request related to a problem? Please describe.**
As The website is under development Wee need a 404 Page for the pages yet to be made.

**Describe the solution you'd like**
Please Create a simple (Or pretty) 404 page for the website with accordance to the rest of the website.
This page will still be used after the completion of the website.

**Comment by maddy020** [comment]
Hey @BeyondSolar 
I would like to work over this issue
Please assign it to me

**Comment by Devemmy01** [comment]
Can I work on the 404 page?

**Comment by sukumar1210** [comment]
> Can I work on the 404 page?

@Devemmy01  Anyone can work on it and create a pull request. If relevant the pull request will be accepted. You don't need to be assigned to work on it.
