### ISSUE TITLE
[FEAT] Make the Website Responsive

### ISSUE THREAD

**Issue by sukumar1210** [VRARMR-juet/VRARMR-juet.github.io#11]
**Is your feature request related to a problem? Please describe.**
The Current Pages are not responsive yet so they need to be made responsive for mobile devices.

Things to be Kept in Mind:
- We need a Hamburger menu for the smaller devices.
- Prefer using the relative units such as `rem` and `%` wherever possible and avoid absolute units such as `px`.

**Comment by Rishav1707** [comment]
Shall I work on this issue? @sukumar1210

**Comment by sukumar1210** [comment]
> Shall I work on this issue? @sukumar1210 

You can if u want to but the pages are still under development. The team is working on the rest of the site and the pages will be up one by one. We were going to work on it after that but extra pair of hands are never criticized.

But know that currently there is not much to work on except the home page. Lemme know if u are still interested.

**Comment by Rishav1707** [comment]
Yes, I like to work on this issue

**Comment by sukumar1210** [comment]
> Yes, I like to work on this issue

Sure then, remember to fork the website into ur profile and deploy it on github pages before a pull request. And send any pull requests to the development branch.

**Comment by Devemmy01** [comment]
Can I work on this?

**Comment by Devemmy01** [comment]
I can add some Javascript as well if needed

**Comment by sukumar1210** [comment]
@Devemmy01 As long as it does not conflict with anything other than it needs to change, yes you are free to use javascript. Kindly go remember the instructions in the description and create any pr for the development branch only. If you may deploy your fork on GitHub pages it will be highly appreciated

**Comment by Devemmy01** [comment]
I noticed the layout of the site is not so good. If I'll have to work on the responsiveness, i'll need to clean and rewrite some code

**Comment by BeyondSolar** [comment]
**Issue Solved -- #53**
Responsiveness Complete for every Page.
